language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Db/DMAqtvD8OaQhXYwqhOFuwpz8L8hUu7ZETdZtDwGKcmejOKJacBQPEeINXQGIRoXu3FmIaB2gnzV4c13YIn5HtItAg93VvfrOsENRwTUstWqq4lLgxyNSzCz8ZQl3GWn0gi3qFCwdLNiWXSDSIq7r/u6c3FX8C9iwyXdozIFYSmFYNWi2kFqjtHhShcfsBbFUrnQuFBdg6Qw55eOIyHPB3AdrLHIWBjU822PL68Eqs+tvc0F/8MPW/ZROzTk4MnkVIrzZRj2gvUi3xdtAj7M/1XX8VK+iyb6CGgAjI56IzSEj0bU0CHjAMtCPNAdOR/51DLxhfMFVD9goVthcDaYhSWd5/rtRMcsKzn/pMTg4cspb0hL3hxWDDRQXgHtuN7T2PtTpaYLb6iaKnsADp2msglm4KS8yEIcrKSwwGliUQNlTmo0H9/XxZu90PDn0SeeW8ixyzQue8hGJEoEQaebQtJ5oMm9MWuOSVGDRvtwynkMF1AxCO/QvDhVwYsTNz44FP9ZyLk0sc1WLvQOnJ87ar1ku/mDg1+UCngkQRaTrVmr962t1DF2aholgVaZMXj1ST4ttig3XSY9/nxbPfIvUbgk1zrzezNngnviCBMwSJyh6awhZd/gZiZR9FhQ7PyPT/RGxZJr+mKaDTy4twdh2YkLFazERkY6nACT2wsRM=
  app: desolate-shelf-63753
  on:
    repo: AndrewPark9517/blogposts-with-database-and-test
