language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: H/Bj5fnmUCCrVTJcw6yjwxLVHqYiMASJK4T6UZWwS8N2wYLqNU4wjYPomiVHIC1Qll51gnxVgu8k9G7jiyU9QV9Gt0/coZPpBrCF7H+kGvV3evLL4EELos0X45RaJhHSCvfN9Vvp+yPzhjFCiK2TRQEeQ96jkvFs5a3d7dE+9MHNijfsJJuhnUEcdoTDDVbQGv/B6HGITdWDu1eENBG6fBuk1nx723yVH3Yo13UfBXLJAOcAhWyIMG7MT003leyzpY3+7kJIkj5jR0Fz8vDHb15vnaAuVK3CrXbgYfnPZNzCSo3Bb+SWWM2mGUBgUpGy3IlCmqsOdYVJQQQ0BRVqbP/zy04lzzdACHsyLZxVUCnplKgTHdLwWlkhtHNAFtD/p0f+bK5zXlT18rbzOxxpLxN8iw8eZKHYPubOKBPs+P/MImVG8iwWwEqNnkX7N6SoaCDvTpX/Xxmm0mkebGztzNgb8AqTwdYcAYk6VE1lVMBwOcNPiRVlJZyjiMBYlyf+jvs3i9pHG8rUrO8hkg4AVYErmjwM7pQZH84mCyoi5K2MEmdCQr31PkikbP9qmGgWyBlw/xGDv8wzRp9bwKKy3hIP3vtj81cILopF/iTLkvAI2tCYNdInKhIlxsORGoCRyD5cr19E0wPxMMGnPmdx4McUz0tDID3zylZZZkmD+fs=
  app: desolate-shelf-63753
  on:
    repo: AndrewPark9517/blogposts-with-database-and-test
